### ISSUE TITLE
Вопрос от Travelpayouts :)

### ISSUE THREAD

**Issue by EngExp** [nikitadev/TravelpayoutsAPI#1]
Здравствуйте, Никита.

Меня зовут Егор, я технический писатель в Travelpayouts. Пишу статью для справочного центра о разных наработках, сделанных с помощью нашего API.

Если Вы не против, я опубликую там ссылку Ваш код https://github.com/nikitadev/TravelpayoutsAPI/. Буду признателен, если найдете пару минут и напишете в двух словах, что он делает и как его использовать. Это существенно ускорит мою работу.

Хорошей недели.
## 

Abramenko Egor
Technical Writer
egor.abramenko@aviasales.ru

**Comment by nikitadev** [comment]
Добрый день.

Егор, Вы где-то ошиблись, так как приведённая ссылка это ссылка на код
Евгения Уткина :)
У меня вот https://github.com/nikitadev/TravelpayoutsAPI, но я не против
если мою опубликуете )
Это обёртка для работы с вашим API для .NET (ASP.NET, WPF). Ставилась цель
покрыть все методы в Travelpayouts API, но в репозитории только методы для
работы с данными из кэша (т.е. API доступа к данным), это:
Цены на авиабилеты
Календарь цен на месяц
Цены по альтернативным направлениям
Самые дешевые авиабилеты
Билеты без пересадок
Билеты из города на любое число месяца
Популярные направления авиакомпании
Данные о странах в json формате
Данные о городах в json формате
Данные об аэропортах в json формате
Данные об авиакомпаниях в json формате
Данные об альянсах в json формате
Данные о самолетах в json формате
Данные о маршрутах в json формате
Определение местоположения пользователя по IP адресу
Специальные предложения.

Например, для Самых дешёвых билетов:

var flights = await _apiFactory.SimpleSearch
                        .GetCheapestTickets(/\* token _/, "MOW", "ULY",
/_ depart date _/, /_ return date */);

Данные возвращаются в уже более удобном виде для работы в коде.
В репозитории есть пример в виде Windows приложения
https://raw.githubusercontent.com/nikitadev/TravelpayoutsAPI/master/publish/setup.exe,
как использовать эту библиотеку.

Фактически на основе этого, _но_ обновлённого API есть приложение для
Windows 10 https://www.microsoft.com/store/apps/9nblggh2rhf4, в котором уже
реализован полноценный поиск (руки не доходят обновить гитхабовский
репозиторий :))

С Уважением,
Никита

**Comment by EngExp** [comment]
Никита, здравствуйте.

Неправильно сначала скопировал ссылку, потом исправил, но Вам видимо пришло уведомление со старой ссылкой :) У меня сейчас в тексте задачи стоит Ваша ссылка :)

Если обновите приложение в github - дайте, пожалуйста, знать :)

Спасибо за информацию.

## 

С уважением,
Абраменко Егор
